title: Alonso Romero Sánchez
#logo: logo path 
#show_downloads: true
theme: jekyll-theme-cayman
description: "Welcome to my GitHub portfolio"
#url: "https://<your-github-username>.github.io"
navbar-links:
  - title: "Home"
    url: "/"
  - title: "About Me"
    url: "/about"
  - title: "Projects"
    url: "/projects"
  - title: "Experience"
    url: "/experience"
  - title: "Contact"
    url: "/contact"

